"""added purchase order tables

Revision ID: 28076bfcdc44
Revises: 629b22629251
Create Date: 2025-08-26 23:45:24.235261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28076bfcdc44'
down_revision: Union[str, Sequence[str], None] = '629b22629251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('dealer_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user', sa.UUID(), nullable=False),
    sa.Column('external_ref_code', sa.String(length=100), nullable=True),
    sa.Column('po_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'INVOICED', 'CANCELLED', name='purchaseorderstatus'), nullable=False),
    sa.Column('total_ex_vat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_inc_vat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('combined_po_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['combined_po_id'], ['purchase_orders.po_id'], ),
    sa.ForeignKeyConstraint(['created_by_user'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.dealer_id'], ),
    sa.PrimaryKeyConstraint('po_id')
    )
    op.create_index(op.f('ix_purchase_orders_created_by_user'), 'purchase_orders', ['created_by_user'], unique=False)
    op.create_index(op.f('ix_purchase_orders_dealer_id'), 'purchase_orders', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_id'), 'purchase_orders', ['po_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_table('purchase_order_items',
    sa.Column('po_item_id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('pack_size_snapshot', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.po_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('po_item_id')
    )
    op.create_index(op.f('ix_purchase_order_items_po_id'), 'purchase_order_items', ['po_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_po_item_id'), 'purchase_order_items', ['po_item_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_product_id'), 'purchase_order_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_order_items_product_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_po_item_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_po_id'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_dealer_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_created_by_user'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
